services:
  gateway:
    build: ./map-gen-gateway/
    ports:
      - "8080:8080"
    environment:
      - API_KEY=1337
      - DATABASE_URL=Host=postgres-db;Database=mapgen;Username=postgres;Password=postgres123
      - LLM_URL=http://llm-service:8000
      - MAPGEN_URL=http://mapgen-service:8080
    depends_on:
      - postgres-db  
        
  llm-service:
    build: ./llm-service/
    environment:
      - GEMINI_KEY=AIzaSyBxTu_P71pj8_EaPAgZLLS0RnolcxkTmEs

  mapgen-service:
    build: ./generator

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mapgen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: